{% set name = "pydiverse-transform" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydiverse_transform-{{ version }}.tar.gz
  sha256: d781a17f1adb7545202edfe29dc23823fe9c154e24cae6d9b894681eb80895fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - poetry
    - pip
    - python >=3.9,<4.0
  run:
    - python >=3.9,<4.0
    - numpy >=1.23.1
    - pandas >=1.4.3
    - sqlalchemy >=1.4.39

test:
  imports:
    - pydiverse.transform
  commands:
    - pip check
  requires:
    - pip

about:
  home: None
  summary: Pipe based dataframe manipulation library that can also transform data on SQL databases
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - windiana42
    - NMAC427
